/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SyLibBase {
    }
    interface SyLibCategoria {
        "id_pai": any;
    }
    interface SyLibClasse {
        "api": any;
        "body": any;
        "identificador": string;
        "nome": any;
    }
    interface SyLibConteudo {
        "id_pai": any;
    }
    interface SyLibObjeto {
        "data_atualizacao": any;
        "data_criacao": any;
        "esta_publicado": boolean;
        "id_pai": any;
        "identificador": any;
        "nome": any;
    }
    interface SyLibPerguntasRepostas {
    }
    interface SyLibServico {
        "id_pai": any;
    }
    interface SyLibTema {
    }
}
declare global {
    interface HTMLSyLibBaseElement extends Components.SyLibBase, HTMLStencilElement {
    }
    var HTMLSyLibBaseElement: {
        prototype: HTMLSyLibBaseElement;
        new (): HTMLSyLibBaseElement;
    };
    interface HTMLSyLibCategoriaElement extends Components.SyLibCategoria, HTMLStencilElement {
    }
    var HTMLSyLibCategoriaElement: {
        prototype: HTMLSyLibCategoriaElement;
        new (): HTMLSyLibCategoriaElement;
    };
    interface HTMLSyLibClasseElement extends Components.SyLibClasse, HTMLStencilElement {
    }
    var HTMLSyLibClasseElement: {
        prototype: HTMLSyLibClasseElement;
        new (): HTMLSyLibClasseElement;
    };
    interface HTMLSyLibConteudoElement extends Components.SyLibConteudo, HTMLStencilElement {
    }
    var HTMLSyLibConteudoElement: {
        prototype: HTMLSyLibConteudoElement;
        new (): HTMLSyLibConteudoElement;
    };
    interface HTMLSyLibObjetoElement extends Components.SyLibObjeto, HTMLStencilElement {
    }
    var HTMLSyLibObjetoElement: {
        prototype: HTMLSyLibObjetoElement;
        new (): HTMLSyLibObjetoElement;
    };
    interface HTMLSyLibPerguntasRepostasElement extends Components.SyLibPerguntasRepostas, HTMLStencilElement {
    }
    var HTMLSyLibPerguntasRepostasElement: {
        prototype: HTMLSyLibPerguntasRepostasElement;
        new (): HTMLSyLibPerguntasRepostasElement;
    };
    interface HTMLSyLibServicoElement extends Components.SyLibServico, HTMLStencilElement {
    }
    var HTMLSyLibServicoElement: {
        prototype: HTMLSyLibServicoElement;
        new (): HTMLSyLibServicoElement;
    };
    interface HTMLSyLibTemaElement extends Components.SyLibTema, HTMLStencilElement {
    }
    var HTMLSyLibTemaElement: {
        prototype: HTMLSyLibTemaElement;
        new (): HTMLSyLibTemaElement;
    };
    interface HTMLElementTagNameMap {
        "sy-lib-base": HTMLSyLibBaseElement;
        "sy-lib-categoria": HTMLSyLibCategoriaElement;
        "sy-lib-classe": HTMLSyLibClasseElement;
        "sy-lib-conteudo": HTMLSyLibConteudoElement;
        "sy-lib-objeto": HTMLSyLibObjetoElement;
        "sy-lib-perguntas-repostas": HTMLSyLibPerguntasRepostasElement;
        "sy-lib-servico": HTMLSyLibServicoElement;
        "sy-lib-tema": HTMLSyLibTemaElement;
    }
}
declare namespace LocalJSX {
    interface SyLibBase {
    }
    interface SyLibCategoria {
        "id_pai"?: any;
    }
    interface SyLibClasse {
        "api"?: any;
        "body"?: any;
        "identificador"?: string;
        "nome"?: any;
    }
    interface SyLibConteudo {
        "id_pai"?: any;
    }
    interface SyLibObjeto {
        "data_atualizacao"?: any;
        "data_criacao"?: any;
        "esta_publicado"?: boolean;
        "id_pai"?: any;
        "identificador"?: any;
        "nome"?: any;
    }
    interface SyLibPerguntasRepostas {
    }
    interface SyLibServico {
        "id_pai"?: any;
    }
    interface SyLibTema {
    }
    interface IntrinsicElements {
        "sy-lib-base": SyLibBase;
        "sy-lib-categoria": SyLibCategoria;
        "sy-lib-classe": SyLibClasse;
        "sy-lib-conteudo": SyLibConteudo;
        "sy-lib-objeto": SyLibObjeto;
        "sy-lib-perguntas-repostas": SyLibPerguntasRepostas;
        "sy-lib-servico": SyLibServico;
        "sy-lib-tema": SyLibTema;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-lib-base": LocalJSX.SyLibBase & JSXBase.HTMLAttributes<HTMLSyLibBaseElement>;
            "sy-lib-categoria": LocalJSX.SyLibCategoria & JSXBase.HTMLAttributes<HTMLSyLibCategoriaElement>;
            "sy-lib-classe": LocalJSX.SyLibClasse & JSXBase.HTMLAttributes<HTMLSyLibClasseElement>;
            "sy-lib-conteudo": LocalJSX.SyLibConteudo & JSXBase.HTMLAttributes<HTMLSyLibConteudoElement>;
            "sy-lib-objeto": LocalJSX.SyLibObjeto & JSXBase.HTMLAttributes<HTMLSyLibObjetoElement>;
            "sy-lib-perguntas-repostas": LocalJSX.SyLibPerguntasRepostas & JSXBase.HTMLAttributes<HTMLSyLibPerguntasRepostasElement>;
            "sy-lib-servico": LocalJSX.SyLibServico & JSXBase.HTMLAttributes<HTMLSyLibServicoElement>;
            "sy-lib-tema": LocalJSX.SyLibTema & JSXBase.HTMLAttributes<HTMLSyLibTemaElement>;
        }
    }
}
